### ISSUE TITLE
Use Ast_mapper.register

### ISSUE THREAD

**Issue by Drup** [janestreet/ppx_driver#1]
I noticed that ppx_driver doesn't use `Ast_mapper.register`. It seems to me that it was made for such a function and it would allow ppx_driver to also work with random ppxs found in the wild. Is there a reason for that ?

If the API is not usable, maybe we could fix it.

cc @alainfrisch

**Comment by diml** [comment]
Do you mean it doesn't set `Ast_mapper.register_function`? I thought about that, it would indeed allow to use any ppx rewriters with ppx\_driver, but you'd have to run the driver with `-no-check` which would suppress most of the benefit of using the driver.

Indeed the driver is able to detect:
- unused attributes (and do spellchecking)
- dropped attributes due to buggy ppx rewriters (and it's extremely easy to do this) 
But for this to work it requires a bit of cooperation from the rewriters (i.e. deal with attributes and extensions through ppx\_core).

So I'm not sure it's really interesting for ppx\_driver to set `Ast_mapper.register_function`.

**Comment by Drup** [comment]
Yes, that's what I meant.

Isn't there also another benefit: speed ? Having only one ppx instead of many successive ppxs.

It seems you could still do 1), which seems the most important. 
I think 2) is useful for developing a ppx, not for ppx usage (It's a bug in the ppx, after all ...). It's all good if ppx_core/drivers provides goodies for ppx developers, but I don't think it should restrict the end user in the ppx he can compose together.

**Comment by diml** [comment]
> Isn't there also another benefit: speed ? Having only one ppx instead of many successive ppxs.

Probably yeah. We didn't actually measure it, but I suppose there is. If that's interesting for users then there is no harm in setting `Ast_mapper.register_function` indeed.

> It seems you could still do 1), which seems the most important. 

How would you do it? You could expect ppx rewriters to remove attributes they use, but then you can't share an attribute between several ppx (such as `[@default]`). Plus you can't distinguish used attributes from attributes dropped by mistake.

> I think 2) is useful for developing a ppx, not for ppx usage (It's a bug in the ppx, after all ...). It's all good if ppx_core/drivers provides goodies for ppx developers, but I don't think it should restrict the end user in the ppx he can compose together.

I think you really want this check in production:
1. it's really hard to write code that doesn't drop attributes, a lot of pattern matchings will implicitly drop attributes. You should always be careful about attributes but it's much easier to accept no caring about attributes in some places and have a global check
2. it's really hard to check that some AST transformation code doesn't drop attributes, either by reading it or with unit tests
3. when a user gets bitten by such a bug, it's really hard to debug

**Comment by Drup** [comment]
> If that's interesting for users

I'm pretty sure it is for (reasonably) big code bases which uses a standard set of extension (ocsigen, mirage, ...). Arguably, if the interest is present, those extension should be converted to use ppx_core, but I think it's still useful. 

> You could expect ppx rewriters to remove attributes they use, but ...

That's what I was thinking, but you have a point. I'm not sure. 

> I think you really want this check in production: ...

I didn't encounter the problem, but maybe mostly because the ppx I wrote are not that complex (lwt and jsoo's transformations are very local ...). Or maybe they are completely buggy from this point of view and I didn't realized it, so I will trust you on that one. :p

**Comment by alainfrisch** [comment]
I had some thoughts about a tool that would check for attribute uses, based on declarative specifications provided by each "package" (ppx, but also potentially other tools that process .cmt/.cmi files or just re-parse the source code).  This would amount to creating a kind of "type system" for attributes, describing the supported attributes with their contexts and possible payload (or an approximation thereof).  Having access to this kind of information would be useful not only for a "checker" tool, but also potentially for IDE/merlin/etc.

**Comment by hhugo** [comment]
Closing since ppx_driver was merged into https://github.com/ocaml-ppx/ppxlib.
Open an issue there if still relevant.
