### ISSUE TITLE
ocamlbuild dependency disappears

### ISSUE THREAD

**Issue by eucpp** [janestreet/ppx_driver#16]
Version 0.9.1 has dependency on `ocambuid` package, but in newer version it disappers from `opam` file. What was happened ? Is it's no longer supported ?
Readme still says that ocambuild is supported.

**Comment by Kakadu** [comment]
It seems that ocamlbuild was dropped at 6486773f323bd5335d53ac1c790f96259a36a9ad

**Comment by hhugo** [comment]
The readme is updated internally, will reach github soon.

**Comment by Kakadu** [comment]
@hhugo Btw, do you know into which package ocamlbuild integration has been moved?

**Comment by diml** [comment]
It was deleted. Do you need ppx_driver specific features? Otherwise you can use the ocaml-migrate-parsetree-ocamlbuild, which provide a similar functionality but with a simplified driver
