### ISSUE TITLE
Standalone ppx rewriter (-as-ppx mode) ignores cookies

### ISSUE THREAD

**Issue by copy** [janestreet/ppx_driver#19]
This causes https://github.com/janestreet/ppx_inline_test/issues/1. `ppx_inline_test` creates error nodes in the ppx if the build system doesn't specify a library name. jbuilder generates a proper `-ppx` flag for merlin including the `--cookie library-name=…` part, but this driver ignores cookies when in `-as-ppx` mode ([`--cookie`](https://github.com/janestreet/ppx_driver/blob/ee1518adba0ac73bb99df958dfbfe56d6f5dce04/src/ppx_driver.ml#L1064) is in `standalone_args` when it should be in `shared_args`).

**Comment by diml** [comment]
Indeed, I fixed this in the v0.10 branch, we are going to do a new release soon

**Comment by hhugo** [comment]
@diml, is this fixed ?

**Comment by ghost** [comment]
yes
