### ISSUE TITLE
constraint opam-version

### ISSUE THREAD

**Issue by ivg** [janestreet/ppx_driver#2]
`js-utils/gen-install.ml` script relies on a feature `libexec`, that was added experimentally only in `opam.1.2.1`. As a result, on older `opam` all ppx rewriters skips the installation of the `ppx` tool, e.g., 

```
Installing ppx_fail.113.24.00.
[WARNING] libexec is an unknown field in /home/vagrant/.opam/4.02.3/build/ppx_fail.113.24.00/ppx_fail.install.
```

This results in confusing error messages in the compilation process of dependent libraries, if this libraries didn't manually add `-predicates` field to `ocamldep` rule (that is not added by default after PR#6184).

**Comment by diml** [comment]
OK, we can change that for the next release, do you know what's the workaround without libexec?

**Comment by ivg** [comment]
The only thing, that I have in mind, is to rollback to the oasis internal installer, and install libexec via the `lib_hook`. (Not sure, that this will even work)

**Comment by hhugo** [comment]
This is likely fixed by the switch to jbuilder.
