### ISSUE TITLE
Using with ppx_deriving

### ISSUE THREAD

**Issue by superbobry** [janestreet/ppx_driver#6]
When used with `ppx_deriving` the driver fails with

```
Error: Attribute `deriving' was not used
```

which implies that `ppx_deriving` was not linked into the driver

```
$ ./_build/ppx-driver-ppx_deriving.show+ppx_inline_test.native -print-transformations
inline-test
```

The contents of `_oasis` and `myocamlbuild.ml` matches the one described in [jane-street-tests/with-oasis-method2](https://github.com/janestreet/jane-street-tests/tree/master/test-inline-tests/with-oasis-method2). 

```
$ cat _tags
<src/*.ml{,i}>: predicate(ppx_custom)
<src/*.ml{,i}>: ppx-driver(ppx_deriving.show+ppx_inline_test -inline-test-lib ook)
<bin/test_runner.*>: linkall
# OASIS_START
# OASIS_END
```

Is this the expected behaviour? Does `ppx_driver` only work for janestreet rewriters?

**Comment by diml** [comment]
Using ppx\_deriving plugins with ppx\_driver is only supported in the development version

**Comment by hhugo** [comment]
I believe this is fixed. reopen otherwise.
