### ISSUE TITLE
`-reconcile` flag looks cool

### ISSUE THREAD

**Issue by bobzhang** [janestreet/ppx_driver#9]
This makes PPX made by Janestreet much more accessible and useful without worrying about compiler versions locked in.
Do you have any design documentation or  what kind of challenges did you overcome? Thanks !

**Comment by diml** [comment]
There is [this blog post](https://blogs.janestreet.com/an-solution-to-the-ppx-versioning-problem/). We didn't use it for versioning in the end and we now rely on ocaml-migrate-parsetree. However we do use deriving_inline for testing or cutting dependencies on ppx, at least in Base

**Comment by bobzhang** [comment]
Hmm, migrate tree looks nice, but it did not really cut dependency and it is still a moving target. I wish -reconcile could work out since it truly cuts the dependency and I don't need worry about my code will get rotten if I used some ppx

**Comment by diml** [comment]
Well -reconcile does work right now, as long as you stick to the context_free api
